<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[3]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[4]=array(0,1,1,'5Lqn5ZOB55+l6K+G');
$cfg_Cs[5]=array(0,1,1,'6ZSA5ZSu572R57uc');
$cfg_Cs[6]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[7]=array(0,1,1,'5Zyo57q/55WZ6KiA');
$cfg_Cs[8]=array(3,1,1,'5LiN6ZSI6ZKi5qmx5p+c57O75YiX');
$cfg_Cs[9]=array(3,1,1,'5LiN6ZSI6ZKi5p+c5L2T57O75YiX');
$cfg_Cs[10]=array(3,1,1,'5LiN6ZSI6ZKi6Zeo5p2/57O75YiX');
$cfg_Cs[11]=array(3,1,1,'5LiN6ZSI6ZKi5Y+w6Z2i57O7');
$cfg_Cs[12]=array(3,1,1,'5LiN6ZSI6ZKi6YWN5Lu257O75YiX');
?>