<?php
$z[0]=Array("global","",1593,1622);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",1784,1813);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",1913,1938);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channel","\r\n<li id=\"nav02\"><a href=\"[field:typeurl/]\" [field:rel/]>[field:typename/]</a></li>\r\n",1959,2170);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li id='nav02'><a href='~typelink~' ~rel~>~typename~</a></li>";

?>